### ISSUE TITLE
KL divergence

### ISSUE THREAD

**Issue by JJQKA2** [rluver/Deep_Temporal_Clustering-Fully_Unsupervised_Learning_of_Time-Domain_Features#1]
In the Temporal Clustering Layer, it seems that you do not use KL divergence as a loss function for clustering？

**Comment by rpycgo** [comment]
Thanks for your comment
I fixed loss

**Comment by rpycgo** [comment]
> In the Temporal Clustering Layer, it seems that you do not use KL divergence as a loss function for clustering？

Thanks for your comment
I fixed loss
